# Generated by Django 4.1 on 2022-08-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_alter_rareuser_profile_image_url'),
        ('app_api', '0003_alter_subscription_ended_on'),
    ]

    operations = [
    ]
