# Generated by Django 4.1 on 2022-08-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_merge_20220817_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reactions', to='app_api.reaction'),
        ),
    ]
