# Generated by Django 4.1 on 2022-08-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_merge_20220817_1816'),
        ('app_api', '0004_merge_20220817_1827'),
        ('app_api', '0004_merge_20220817_1836'),
    ]

    operations = [
    ]
