# Generated by Django 4.1 on 2022-08-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_merge_20220817_1827'),
        ('app_api', '0004_merge_20220817_1836'),
        ('app_api', '0005_alter_postreaction_reaction'),
    ]

    operations = [
    ]
