# Generated by Django 4.1 on 2022-08-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_merge_20220818_1336'),
        ('app_api', '0006_merge_20220818_1417'),
    ]

    operations = [
    ]
