# Generated by Django 4.1 on 2022-08-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_merge_20220817_2021'),
        ('app_api', '0007_alter_post_image_url_demotionqueue'),
    ]

    operations = [
    ]
