# Generated by Django 4.1 on 2022-08-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_alter_post_image_url_demotionqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='profile_image_url',
            field=models.ImageField(default='', null=True, upload_to='actionimages'),
        ),
    ]
