# Generated by Django 4.1 on 2022-08-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0008_alter_rareuser_active_alter_rareuser_created_on_and_more'),
        ('app_api', '0008_merge_20220818_1849'),
    ]

    operations = [
    ]
