# Generated by Django 4.1 on 2022-08-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_merge_20220818_1620'),
        ('app_api', '0009_merge_20220818_2025'),
    ]

    operations = [
    ]
